import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3/sqlite3.dart';
import 'package:sqlite3_flutter_libs/sqlite3_flutter_libs.dart';
import 'package:turon_tour/data/db/daos/agent_dao.dart';
import 'package:turon_tour/data/db/daos/user_dao.dart';
import 'package:turon_tour/data/db/tables.dart';

// Generated by build_runner:
//   dart run build_runner build --delete-conflicting-outputs
part 'app_database.g.dart';

@DriftDatabase(tables: [Users, Agents], daos: [UserDao, AgentDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Test / DI constructor allowing an in-memory or custom executor.
  AppDatabase.forExecutor(super.executor);

  @override
  int get schemaVersion => 1;
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'turon_tour.sqlite'));

    // Work around old Android sqlite versions and temp-dir issues.
    await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
    sqlite3.tempDirectory = (await getTemporaryDirectory()).path;

    return NativeDatabase.createInBackground(file);
  });
}
