import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqlite3/sqlite3.dart';
import 'package:sqlite3_flutter_libs/sqlite3_flutter_libs.dart';
import 'package:turon_tour/data/db/converters.dart';
import 'package:turon_tour/data/db/daos/agent_dao.dart';
import 'package:turon_tour/data/db/daos/user_dao.dart';
import 'package:turon_tour/data/db/tables.dart';
import 'package:turon_tour/domain/entities/localized.dart';

// Generated by build_runner:
//   dart run build_runner build --delete-conflicting-outputs
part 'app_database.g.dart';

@DriftDatabase(
  tables: [
    Users,
    Agents,
    Tours,
    SeriesDepartures,
    Bookings,
    PaymentInstallments,
    Vouchers,
    Reviews,
    Wishlists,
  ],
  daos: [UserDao, AgentDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Test / DI constructor allowing an in-memory or custom executor.
  AppDatabase.forExecutor(super.executor);

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        onUpgrade: (m, from, to) async {
          // This is a mock/demo app whose data comes entirely from the seeder.
          // Rather than write incremental migrations, wipe and recreate on any
          // upgrade — the seeder repopulates on next launch.
          await customStatement('PRAGMA foreign_keys = OFF');
          for (final entity in allSchemaEntities) {
            await m.drop(entity);
          }
          await m.createAll();
          await customStatement('PRAGMA foreign_keys = ON');
        },
      );
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'turon_tour.sqlite'));

    // Work around old Android sqlite versions and temp-dir issues.
    await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
    sqlite3.tempDirectory = (await getTemporaryDirectory()).path;

    return NativeDatabase.createInBackground(file);
  });
}
